### ISSUE TITLE
gene_pos.Robj broken

### ISSUE THREAD

**Issue by floriankreten** [dkzhang777/SlideCNA_Analysis#1]
Hi guys, I am trying to get into this program. Unfortunately the gene_pos.Robj seems to be broken.

**Comment by JWatter** [comment]
Hi,
could you tell us where the error occurs (i.e. which line you were running) and what the error message is?

I just opened gene_pos.Robj and it did not give me any problems, so I expect the error to be somewhere else

**Comment by floriankreten** [comment]
Re-downloaded the file and it works, sorry for the messup :)
